//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAppDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class caso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public caso()
        {
            this.solucions = new HashSet<solucion>();
            this.valoracion_respuesta = new HashSet<valoracion_respuesta>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string codigo_usuario { get; set; }
        public string relevancia { get; set; }
        public string tipo_caso { get; set; }
        public Nullable<int> id_queja { get; set; }
        public Nullable<int> id_reclamo { get; set; }
        public Nullable<int> id_departamento { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string Comentario { get; set; }
        public string estatus { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual Estatu Estatu { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual queja queja { get; set; }
        public virtual reclamo reclamo { get; set; }
        public virtual Relevancia Relevancia1 { get; set; }
        public virtual Tipo_Caso Tipo_Caso1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<solucion> solucions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<valoracion_respuesta> valoracion_respuesta { get; set; }
        public virtual departamento departamento { get; set; }
    }
}
