//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAppDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.casoes = new HashSet<caso>();
            this.producto_cliente = new HashSet<producto_cliente>();
            this.valoracion_respuesta = new HashSet<valoracion_respuesta>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string clave { get; set; }
        public string cedula { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string correo { get; set; }
        public string estatus { get; set; }
        public Nullable<decimal> monto { get; set; }
        public string telefono { get; set; }
        public string cargo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caso> casoes { get; set; }
        public virtual Esta_Usua_clien Esta_Usua_clien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto_cliente> producto_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<valoracion_respuesta> valoracion_respuesta { get; set; }
    }
}
