//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAppDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServiceAppEntities1 : DbContext
    {
        public ServiceAppEntities1()
            : base("name=ServiceAppEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<caso> casoes { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<departamento> departamentoes { get; set; }
        public virtual DbSet<Esta_Usua_clien> Esta_Usua_clien { get; set; }
        public virtual DbSet<Estatu> Estatus { get; set; }
        public virtual DbSet<modulo> moduloes { get; set; }
        public virtual DbSet<Operacion> Operacions { get; set; }
        public virtual DbSet<producto> productoes { get; set; }
        public virtual DbSet<producto_cliente> producto_cliente { get; set; }
        public virtual DbSet<queja> quejas { get; set; }
        public virtual DbSet<reclamo> reclamoes { get; set; }
        public virtual DbSet<Relevancia> Relevancias { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<Rol_Operacion> Rol_Operacion { get; set; }
        public virtual DbSet<solucion> solucions { get; set; }
        public virtual DbSet<Tipo_Caso> Tipo_Caso { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<valoracion_respuesta> valoracion_respuesta { get; set; }
    }
}
