//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAppDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class solucion
    {
        public int id { get; set; }
        public Nullable<int> id_caso { get; set; }
        public string ComenSolu { get; set; }
    
        public virtual caso caso { get; set; }
    }
}
