//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAppDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.casoes = new HashSet<caso>();
            this.valoracion_respuesta = new HashSet<valoracion_respuesta>();
        }
    
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string clave { get; set; }
        public string estatus { get; set; }
        public Nullable<int> Id_departamento { get; set; }
        public string cargo { get; set; }
        public Nullable<int> idroll { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string TipoUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caso> casoes { get; set; }
        public virtual departamento departamento { get; set; }
        public virtual Esta_Usua_clien Esta_Usua_clien { get; set; }
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<valoracion_respuesta> valoracion_respuesta { get; set; }
    }
}
