//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceAppDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class valoracion_respuesta
    {
        public int id { get; set; }
        public Nullable<int> id_caso { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string id_usuario { get; set; }
        public Nullable<decimal> valor { get; set; }
    
        public virtual caso caso { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
